shared:
  node.0.1

  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://artifactory-postgres:5432/artifactory
    username: artifactory
    password: ArtifactoryPostgres123!

router:
  entrypoints:
    externalPort: 8082
frontend:
    session:
        timeMinutes: 60
