FROM releases-docker.jfrog.io/jfrog/artifactory-oss:7.146.25

LABEL org.opencontainers.image.title="Artifactory OSS personalizado para laboratorio DevOps"
LABEL org.opencontainers.image.description="Artifactory OSS preparado para despliegue con Terraform."
LABEL org.opencontainers.image.vendor="DevOps Lab"