FROM jenkins/jenkins:lts-jdk17

USER root
RUN apt-get update     && apt-get install -y --no-install-recommends docker.io curl ca-certificates     && rm -rf /var/lib/apt/lists/*

USER jenkins
COPY config/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt
COPY config/init-admin-users.groovy /usr/share/jenkins/ref/init.groovy.d/init-admin-users.groovy
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
